// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

function fibonacci(n) {
    // http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibFormula.html
    return Math.round(Math.pow(((Math.sqrt(5) + 1)/2), n)/Math.sqrt(5));
}

function isEven(n) {
    return !(n&1);
}

function sumEvenFibs(limit) {
    let sum=0;
    let i = 2; // start one before the first even fib
    let fib = fibonacci(i); 
    do {
        if(isEven(fib)) {
            sum += fib;
        }
        i++;
        fib = fibonacci(i);
    } while (fib <= limit);
    return sum;
}

console.log(sumEvenFibs(4000000));
